# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96b8a52704128960681373c4f61eb950c96f8f7b1e5e19b43eb02d36cbd40f2022dff1d8c12a6dd19afa277ccb75fd1a2bef281c9dc88305b74282b02274cbb

test:
  secret_key_base: 70bc54e4d69026d8b9e4ba3c1c11dcddd431efb85df9e2b4a8f7b492ee61eeab488c82db814ef2bdf26e059182a42c40ecea9e1d9fdaa374bd0756869d532bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
